### ISSUE TITLE
Issue with node v0.12

### ISSUE THREAD

**Issue by ankitpatial** [marcloney/freshbooks.js#11]
installing freshbookjs package on latest node v0.12 is failing because of libxmljs.
I tried installing libxmljs v0.13.0 package and it installed perfectly. 
In freshbookjs libxmljs v0.8.1 is in use,  to make it work I guess you need to upgrade it libxmljs to latest version.

**Comment by droppedoncaprica** [comment]
Just to follow up on this, I'm currently looking at the failing tests.  It appears as though the Client tests fail due to a limit on the amount of Clients we can create using the freshbooksjs.freshbooks.com account.

I've opened a ticket to Freshbooks asking if these Client errors we are seeing are due to an account limit.  If the errors we're seeing are from an account restriction, it looks like there's only a single test to fix until this library works with Node.js 12.x.
